name: Compare tables and send diff by email

# Configure Manual Trigger
on:
  workflow_dispatch:

jobs:
  compare-tables-and-send-email:
    runs-on: ubuntu-latest
    permissions:                # Job-level permissions configuration starts here
      contents: write           # 'write' access to repository contents
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Setup Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12' # Install the Python version needed

      # Step 3: Install dependencies
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Execute the Python script to create a CSV
      - name: Compare tables
        env:
          URL: ${{ secrets.URL }}
          EMAIL_RECEIVER_LIST: ${{ secrets.EMAIL_RECEIVER_LIST }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
          EMAIL_SUBJECT: ${{ secrets.EMAIL_SUBJECT }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          PORT: ${{ secrets.PORT }}
        run: python main.py

      # Step 5: Commit and push the generated CSV file if there are changes
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add tables/*.csv
          git commit -a -m "Add changes"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          directory: .
          force: true